### PR TITLE
Add support for platform specific arguments

### PR DESCRIPTION
**Pull request by dmikusa**
## Summary

This PR adds support for platform-specific arguments in the `stack.toml` file for use when creating multi-architecture stacks.

The Build and Run settings can contain arguments, i.e. `[build.args]`. The same set of arguments is applied across all of the platforms. However, in some cases, it is necessary to have platform-specific arguments. To do this you can define `[build.platforms.<platform>]` and supply a list of arguments. The platform-specific arguments are overlaid on the general arguments, so you can override general args with platform-specific ones or add more arguments.

## Use Cases

When building Ubuntu mult-arch images, sources are different for amd64 and arm64. The stacks define a set of sources as arguments.

```
  [build.args]
    sources = """
    deb http://archive.ubuntu.com/ubuntu jammy main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-updates main universe multiverse
    deb http://archive.ubuntu.com/ubuntu jammy-security main universe multiverse
    """
```

These need to be different depending on the architecture. This PR allows you to define an override per-platform.

```
  [build.platforms."linux/arm64"]
    sources = """
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-updates main universe multiverse
    deb http://ports.ubuntu.com/ubuntu-ports/ jammy-security main universe multiverse
    """
```

When that particular platform builds, jam will provide the platform-specific arguments so that the correct sources are used for that architecture.

## Outstanding Questions

- The structure that is currently being used in the TOML file won't be totally flexible. It assumes that the only platform-specific data will be arguments, i.e. `[build.platforms."linux/arm64"]` is a map of arguments. It does this to make the config file format a little easier and because we only need platform-specific args, but if we foresee the need to have other platform-specific data, then I can update the PR so that `[build.platforms."linux/arm64".args]` would be the key. Just let me know.
- The method `func (i DefinitionImage) Arguments() ([]string, error)` is changed in this PR to `func (i DefinitionImage) Arguments(platform string) ([]string, error)`. That is changing the function signature. I think that should be OK because it's in an internal package. Just wanted to call that out. If needed, I can make a second function that takes the platform and retain the existing method. Again, just let me know if that is preferred.

## Checklist

* [x] I have viewed, signed, and submitted the Contributor License Agreement.
* [x] I have linked issue(s) that this PR should close using keywords or the Github UI (See [docs](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue))
* [x] I have added an integration test, if necessary.
* [x] I have reviewed the [styleguide](https://github.com/paketo-buildpacks/community/blob/main/STYLEGUIDE.md) for guidance on my code quality.
* [x] I'm happy with the commit history on this PR (I have rebased/squashed as needed).

### CODE REVIEW

**Review by robdimsdale — COMMENTED** [review]
Thanks for putting this together.

As far as `[build.platforms."linux/arm64"]` vs `[build.platforms."linux/arm64".args]`, I'd have a slight preference for the latter. Not because I have a concrete expectation to add other fields beyond `args` but because i prefer the symmetry of `build.args` and `build.platforms.some-platform-override.args`. The fact that it is more future-proofed is a nice bonus. If you're willing and able to make that change I think that would be great.

I'm fine with making breaking changes to `internal` packages.

Also, I notice this PR doesn't add an integration test for the overrides. The integration tests already validate that we build stacks with multiple platforms, but I think it could be helpful to validate the override feature works at the integration-test level as well as the unit-test level. Do you agree?

**Comment by dmikusa** [comment]
>As far as [build.platforms."linux/arm64"] vs [build.platforms."linux/arm64".args], I'd have a slight preference for the latter. Not because I have a concrete expectation to add other fields beyond args but because i prefer the symmetry of build.args and build.platforms.some-platform-override.args. The fact that it is more future-proofed is a nice bonus. If you're willing and able to make that change I think that would be great.

Sure. I can add that.

>Also, I notice this PR doesn't add an integration test for the overrides. The integration tests already validate that we build stacks with multiple platforms, but I think it could be helpful to validate the override feature works at the integration-test level as well as the unit-test level. Do you agree?

I missed the integration tests, so I hadn't thought about it. My vote is that it's probably covered well enough with the unit tests, but if it's easy to add to an existing integration I can do so. I'll take a look.

**Comment by dmikusa** [comment]
>The structure that is currently being used in the TOML file won't be totally flexible. It assumes that the only platform-specific data will be arguments, i.e. [build.platforms."linux/arm64"] is a map of arguments. It does this to make the config file format a little easier and because we only need platform-specific args, but if we foresee the need to have other platform-specific data, then I can update the PR so that [build.platforms."linux/arm64".args] would be the key. Just let me know.

Changed. It now requires `.args`.

>The method func (i DefinitionImage) Arguments() ([]string, error) is changed in this PR to func (i DefinitionImage) Arguments(platform string) ([]string, error). That is changing the function signature. I think that should be OK because it's in an internal package. Just wanted to call that out. If needed, I can make a second function that takes the platform and retain the existing method. Again, just let me know if that is preferred.

I also added something to the integration test. It's not a new test, but I modified an existing test to also have some platform-specific settings, which I made the Dockerfiles just set as labels so the test could easily verify them.

**Review by robdimsdale — DISMISSED** [review]
This looks great. Thanks for making the change to the structure and to the integration test.

I think the integration test serves two purposes: 1) validating the end-to-end aspect of the feature works and 2) demonstrating how to actually use this feature in practice with a valid `stack.toml` file. I think both of those aspects make the test worthwhile, so thanks for working on that.

**Comment by robdimsdale** [comment]
Other @paketo-buildpacks/stacks-maintainers if you 👍 then feel free to merge when you're ready

**Review by sophiewigmore — APPROVED** [review]

**Pull request merged**
